### ISSUE TITLE
v3.6.1 comes with broken bash invocation

### ISSUE THREAD

**Issue by Heimrych** [lachie83/k8s-helm#95]
I'm using latest image and started having issues regarding invoking bash directly on the shell. The example below stopped working.

`bash script.sh` 

I debugged a little bit and found out that the image with tag v3.6.1 has bash installed, however it appears to be installed in a broken state. I can't call it through the shell like the previous versions.

A temporary solution would be to delete bash and reinstall, as that fixes the issue.

`apk del bash && apk add bash`

I tested with older images and all work except v3.6.1. Unfortunately, I couldn't find why this happens or even reproduce the scenario with the error ocurring. For now, we settled with using older Helm version but would really appreciate a fix on the new version.

**Comment by jiphex** [comment]
It looks like the apk setup on v3.6.1 is broken - `apk list` shows git to be installed, but the binary isn't present, so `apk add git` doesn't work (because it's already installed)

**Comment by Heimrych** [comment]
v3.6.2 also comes with broken bash invocation

**Comment by MartinKirchner** [comment]
Commit f3155bc4650ec5a218d1e4e0af8112a9622799b6 also broke the git installation, since then it is not installed anymore.
If you replace the `&&` with a semicolon it works again:

```
RUN apk add --update ca-certificates \
 ; apk add -t deps \
 ; apk add -t wget \
 ; apk add -t git \
 ; apk add -t openssl \
 ; apk add -t bash \
 ; wget -q https://get.helm.sh/helm-${HELM_LATEST_VERSION}-linux-${TARGETARCH}.tar.gz \
 && tar -xf helm-${HELM_LATEST_VERSION}-linux-${TARGETARCH}.tar.gz \
 && mv linux-${TARGETARCH}/helm /usr/local/bin \
 && apk del --purge deps \
 && rm /var/cache/apk/* \
 && rm -f /helm-${HELM_LATEST_VERSION}-linux-${TARGETARCH}.tar.gz
```

or revert to:
```
RUN apk add --update ca-certificates \
 && apk add --update -t deps wget git openssl bash \
 && wget -q https://get.helm.sh/helm-${HELM_LATEST_VERSION}-linux-${TARGETARCH}.tar.gz \
 && tar -xf helm-${HELM_LATEST_VERSION}-linux-${TARGETARCH}.tar.gz \
 && mv linux-${TARGETARCH}/helm /usr/local/bin \
 && apk del --purge deps \
 && rm /var/cache/apk/* \
 && rm -f /helm-${HELM_LATEST_VERSION}-linux-${TARGETARCH}.tar.gz
```

**Comment by lachie83** [comment]
Thanks for raising this and sorry for the breakage. I've fixed on the latest tag. LMK if you want me to backport the fix to specific releases. latest currently points to v3.7.0

```
$ docker run -it --entrypoint ash lachlanevenson/k8s-helm:latest
Unable to find image 'lachlanevenson/k8s-helm:latest' locally
latest: Pulling from lachlanevenson/k8s-helm
a0d0a0d46f8b: Already exists
41588b9f5429: Pull complete
Digest: sha256:b575e5e9813508f743830667830edf96ef0381618303ba615e70362fd80d0900
Status: Downloaded newer image for lachlanevenson/k8s-helm:latest
/ # exit
```

**Comment by jrsherry** [comment]
@lachie83, I'm not sure this is truly resolved.  I just pulled the 3.7.0 image and there are still missing binaries (like git) that should be present in the image.
